# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Choctaw spellchecker"
cho = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Choctaw, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
cho = "TRANSLATE: A spellchecker for Choctaw, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.cho"

[windows]
system_product_code = "{D1121392-E248-413C-B3B9-23F02EA6F152}_is1"

[package.speller]
name = "Choctaw"
version = "0.1.0"

[package.grammar]
name = "Choctaw"
version = "0.1.0"

[package.tts-textproc]
name = "Choctaw"
version = "0.1.0"

[package.hyphenator]
name = "Choctaw"
version = "0.1.0"
