template = ""
rev_id = 101
template_sha = "4e8cec0740306225ea834d6a2ce36f612bb6ef07"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
