template = ""
rev_id = 153
template_sha = "ca1a4ee19d234d19c768d1d0646f1a87a67bc6d7"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
