template = ""
rev_id = 105
template_sha = "2118a7f3edb13aaca9a5a0693d18f3374ba5faa0"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
