template = ""
rev_id = 198
template_sha = "c528583032290536023c7e6a65d4f1a65dcb0d30"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
