template = ""
rev_id = 132
template_sha = "c9b931f62e94149b088c740ef7565270a9ed98e5"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
