template = ""
rev_id = 84
template_sha = "1bf63f9aab2789bc3a82ba10d3e5e88c52ed4929"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
