template = ""
rev_id = 77
template_sha = "0e397b985c7c0a4703eee3c093c0d443b12ed1a2"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-cho"
__UND2C__ = "cho"
__UNDEFINED__ = "Choctaw"
__UND__ = "cho"
